server: 
  port: 3344 
  
spring:
  application:
    name:  xc-service-config
  cloud:
    config:
      server: 
        git:
          uri: https://github.com/chrilwe/xuecheng.git #GitHub上面的git仓库名字
 