server:
  port: 60000
spring: 
  application:
    name: xc-service-center-order
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/xc_order?characterEncoding=utf-8
      username: root
      password: root
      driverClassName: com.mysql.jdbc.Driver
      initialSize: 5  #初始建立连接数量
      minIdle: 5  #最小连接数量
      maxActive: 20 #最大连接数量
      maxWait: 10000  #获取连接最大等待时间，毫秒
      testOnBorrow: true #申请连接时检测连接是否有效
      testOnReturn: false #归还连接时检测连接是否有效
      timeBetweenEvictionRunsMillis: 60000 #配置间隔检测连接是否有效的时间（单位是毫秒）
      minEvictableIdleTimeMillis: 300000  #连接在连接池的最小生存时间（毫秒） 

xuecheng: 
  order: 
    store_id: 12
    order_pay_no_ttl: 15 #订单支付超时时间（分钟）
    log_path: F:/xuecheng/logs/

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations:
  - classpath:mapper/**.xml
  
eureka: 
  client: #客户端注册进eureka服务列表内
    service-url: 
      defaultZone: http://localhost:50101/eureka/
       #defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/      
  instance:
    instance-id: xc-service-center-order
    prefer-ip-address: true     #访问路径可以显示IP地址     

info: 
  app.name: xc-service-center-order
  company.name: www.xuecheng.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$