server:
  port: 22100
spring:
  application:
    name: xc-service-base-filesystem
  data:
    mongodb:
      uri: mongodb://admin:123@localhost:27017
      database: xc_cms
  servlet:
    multipart:
      #默认支持文件上传.
      enabled: true
      #支持文件写入磁盘.
      file-size-threshold: 0
      # 上传文件的临时目录
      location:
      # 最大支持文件大小
      max-file-size: 1MB
      # 最大支持请求大小
      max-request-size: 30MB
      
xuecheng: 
  fastdfs:
    connect_timeout_in_seconds: 5
    network_timeout_in_seconds: 30
    charset: UTF-8
    tracker_servers: 192.168.25.133:22122 #多个 trackerServer中间以逗号分隔
        
eureka: 
  client: #客户端注册进eureka服务列表内
    service-url: 
      defaultZone: http://localhost:50101/eureka/
       #defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/      
  instance:
    instance-id: xc-service-base-filesystem
    prefer-ip-address: true     #访问路径可以显示IP地址     

info: 
  app.name: xc-service-manage-cms
  company.name: www.xuecheng.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$